name: penv
channels:
  - defaults
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - pip
  - seaborn
  - matplotlib
  - statsmodels
  - scipy
  - catboost
  - category_encoders
  - japanize_matplotlib
  - matplotlib_venn
  - packaging
  - tqdm
  - xgboost
  - ipywidgets
  - lightgbm